### ISSUE TITLE
Remove authentication from readme

### ISSUE THREAD

**Issue by Lrss** [bitcart/bitcart-woocommerce#1]
After  commit ad236285833586b4b15e101797841b59fe70858b there is no longer authentication fields to be filled in Wordpress so the following should be removed from the readme:   
https://github.com/bitcartcc/bitcart-woocommerce/blob/ad236285833586b4b15e101797841b59fe70858b/readme.txt#L67

**Comment by MrNaif2018** [comment]
Thank you for pointing out! Will fix it now
Done (:
